server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json, text/html
spring:
  application:
    name: coaches
  data:
    mongodb:
      host: localhost
      port: 27017
      database: coaches